FROM node:23.11.0-alpine3.21

ENV RUN_TESTS=true

WORKDIR /usr/app/

RUN npm install -g npm@11.4.1

COPY ./tests/docker/package.json ./package.json
# RUN npm install --save kubo-rpc-client
# RUN yarn install --frozen-lockfile --network-timeout 1000000
RUN npm install


COPY ./tests/docker/tsconfig.test-container.json ./tsconfig.json

COPY ./src/ src/

COPY ./tests/unit/ tests/unit/

COPY ./tests/docker/entrypoint.test.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

ENTRYPOINT [ "/bin/sh", "-c", "./entrypoint.sh" ]