FROM node:23.11.0-alpine3.21

ENV KUBO_VERSION=0.35.0
ENV KUBO_BINARY=/usr/local/bin/ipfs
ENV RUN_TESTS=true

WORKDIR /usr/app/

RUN apk add --no-cache bash curl tar libc6-compat

COPY ./package.json ./
RUN yarn install

COPY ./tests/docker/tsconfig.test-container.json ./tsconfig.json
COPY ./tests/docker/jest.config.mjs ./jest.config.mjs

COPY ./src/ src/

COPY ./tests/unit/ tests/unit/

COPY ./tests/docker/entrypoint.test.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

ENTRYPOINT [ "/bin/sh", "-c", "./entrypoint.sh" ]