FROM node:21.5-bookworm-slim

WORKDIR /usr/app/webapp/

RUN apt update && \ 
    apt install -y git

COPY package*.json ./

RUN npm install -g \ 
    npm@10.3.0 \
    babel-cli webpack \
    serve@14.2.1

RUN npm install

COPY tsconfig.json ./tsconfig.json

RUN git clone https://github.com/orbitdb/orbitdb.git && \
    cd orbitdb && \
    git checkout helia && \
    npm install && \
    npm link

# RUN cd /usr/app/webapp/src && \
#     npm link @orbitdb/core

RUN npm install execa signal-exit

COPY src/ src/

RUN npm run build

RUN cd build && \
    npm link @orbitdb/core

RUN cp ./src/swarm.key ./build/swarm.key

COPY ./entrypoint.sh ./entrypoint.sh

EXPOSE 3000 5001 5002

CMD ["node", "./build/index.js", "--trace-deprecation"]




